In [2]:
import pandas as pd

df =  pd.read_csv('./data/gene_info/gene_info', sep='\t', low_memory=False, nrows=1000)

df.head()

,#tax_id,GeneID,Symbol,LocusTag,Synonyms,dbXrefs,chromosome,map_location,description,type_of_gene,Symbol_from_nomenclature_authority,Full_name_from_nomenclature_authority,Nomenclature_status,Other_designations,Modification_date,Feature_type
0,7,5692769,NEWENTRY,-,-,-,-,-,Record to support submission of GeneRIFs for a...,other,-,-,-,-,20241113,-
1,9,2827857,NEWENTRY,-,-,-,-,-,Record to support submission of GeneRIFs for a...,other,-,-,-,-,20241113,-
2,11,10823747,NEWENTRY,-,-,-,-,-,Record to support submission of GeneRIFs for a...,other,-,-,-,-,20241101,-
3,14,6951813,NEWENTRY,-,-,-,-,-,Record to support submission of GeneRIFs for a...,other,-,-,-,-,20241204,-
4,19,3758873,NEWENTRY,-,-,-,-,-,Record to support submission of GeneRIFs for a...,other,-,-,-,-,20241204,-

In [52]:
df.shape

1000

In [4]:
df.columns

Index(['#tax_id', 'GeneID', 'Symbol', 'LocusTag', 'Synonyms', 'dbXrefs',
       'chromosome', 'map_location', 'description', 'type_of_gene',
       'Symbol_from_nomenclature_authority',
       'Full_name_from_nomenclature_authority', 'Nomenclature_status',
       'Other_designations', 'Modification_date', 'Feature_type'],
      dtype='str')

In [51]:
df['type_of_gene'].value_counts().index[df['type_of_gene'].value_counts().argmax()]

'protein-coding'

In [63]:
print(', '.join(df['type_of_gene'].unique().tolist()))

other, protein-coding, pseudo, rRNA, tRNA

In [6]:
df['Feature_type'].value_counts()

Feature_type
-    1000
Name: count, dtype: int64

In [7]:
df['Symbol'].value_counts()

Symbol
NEWENTRY         6
rrf              5
hemG             2
moaA             2
cyoE             2
                ..
JEZ96_RS04990    1
nagK             1
nagB-II          1
nagA             1
nagX             1
Name: count, Length: 981, dtype: int64

In [8]:
df['Nomenclature_status'].value_counts()

Nomenclature_status
-    1000
Name: count, dtype: int64

In [9]:
df['LocusTag'].value_counts()

LocusTag
-                6
JEZ96_RS00005    1
JEZ96_RS00010    1
JEZ96_RS00015    1
JEZ96_RS00020    1
                ..
JEZ96_RS04990    1
JEZ96_RS04995    1
JEZ96_RS05000    1
JEZ96_RS05005    1
JEZ96_RS05010    1
Name: count, Length: 995, dtype: int64

In [10]:
df['dbXrefs'].value_counts()

dbXrefs
-    1000
Name: count, dtype: int64

In [11]:
df['map_location'].value_counts()

map_location
-    1000
Name: count, dtype: int64

In [12]:
df['description'].value_counts()

description
hypothetical protein                                  94
pseudo                                                15
methyl-accepting chemotaxis protein                   13
response regulator transcription factor                9
ATP-binding protein                                    8
                                                      ..
LacI family DNA-binding transcriptional regulator      1
family 20 glycosylhydrolase                            1
glucosamine-6-phosphate deaminase NagB-II              1
N-acetylglucosamine-6-phosphate deacetylase            1
transmembrane glucosamine N-acetyltransferase NagX     1
Name: count, Length: 731, dtype: int64

In [53]:
df[df['#tax_id'] == 9606].shape[0]

0

In [66]:
df =  pd.read_csv('./data/gene_info/gene_info', sep='\t', low_memory=False, usecols=['#tax_id', 'type_of_gene'], nrows=1000)

In [67]:
df

     #tax_id    type_of_gene
0          7           other
1          9           other
2         11           other
3         14           other
4         19           other
..       ...             ...
995       24  protein-coding
996       24          pseudo
997       24  protein-coding
998       24  protein-coding
999       24  protein-coding

[1000 rows x 2 columns]